<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-bb62276ab45c84d9efd712f51ff97b5a.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Rodian Fonseca Campuzano">
  <meta name="dcterms.date" content="2026-10-02">
  <title>Revisiones Sistemáticas y Metaanálisis en Investigación Biológica</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #24292e;  }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #24292e; } /* Normal */
    code span.al { color: #ff5555; font-weight: bold; } /* Alert */
    code span.an { color: #6a737d; } /* Annotation */
    code span.at { color: #d73a49; } /* Attribute */
    code span.bn { color: #005cc5; } /* BaseN */
    code span.bu { color: #d73a49; } /* BuiltIn */
    code span.cf { color: #d73a49; } /* ControlFlow */
    code span.ch { color: #032f62; } /* Char */
    code span.cn { color: #005cc5; } /* Constant */
    code span.co { color: #6a737d; } /* Comment */
    code span.cv { color: #6a737d; } /* CommentVar */
    code span.do { color: #6a737d; } /* Documentation */
    code span.dt { color: #d73a49; } /* DataType */
    code span.dv { color: #005cc5; } /* DecVal */
    code span.er { color: #ff5555; text-decoration: underline; } /* Error */
    code span.ex { color: #d73a49; font-weight: bold; } /* Extension */
    code span.fl { color: #005cc5; } /* Float */
    code span.fu { color: #6f42c1; } /* Function */
    code span.im { color: #032f62; } /* Import */
    code span.in { color: #6a737d; } /* Information */
    code span.kw { color: #d73a49; } /* Keyword */
    code span.op { color: #24292e; } /* Operator */
    code span.ot { color: #6f42c1; } /* Other */
    code span.pp { color: #d73a49; } /* Preprocessor */
    code span.re { color: #6a737d; } /* RegionMarker */
    code span.sc { color: #005cc5; } /* SpecialChar */
    code span.ss { color: #032f62; } /* SpecialString */
    code span.st { color: #032f62; } /* String */
    code span.va { color: #e36209; } /* Variable */
    code span.vs { color: #032f62; } /* VerbatimString */
    code span.wa { color: #ff5555; } /* Warning */
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-03ee58d93aa56ae2ee8298346d0b2a97.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" center-title-slide="false" data-background-image="title.png" data-background-opacity="0.7" data-background-size="contain" data-footer="none" class="quarto-title-block center">
  <h1 class="title">Revisiones Sistemáticas y Metaanálisis en Investigación Biológica</h1>
  <p class="subtitle">Fundamentos Metodológicos, Herramientas Digitales e Implicaciones Éticas de la IA</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Rodian Fonseca Campuzano
</div>
</div>
</div>

  <p class="date">2026-10-02</p>
</section>
<section id="contenido" class="slide level2">
<h2>Contenido</h2>
<ol type="1">
<li><p><strong>Fundamentos y Tipología de la Síntesis de Evidencia</strong></p></li>
<li><p><strong>Marcos Conceptuales y Estándares de Reporte</strong></p></li>
<li><p><strong>Fases en el Desarrollo Metodológico</strong></p></li>
<li><p><strong>Síntesis Cuantitativa y Metaanálisis</strong></p></li>
<li><p><strong>Ecosistema de Herramientas Digitales e IA</strong></p></li>
<li><p><strong>Desafíos Éticos e Implicaciones</strong></p></li>
<li><p><strong>Ejemplos Prácticos en Biología</strong></p></li>
<li><p><strong>Conclusiones</strong></p></li>
</ol>
</section>
<section>
<section id="fundamentos-y-tipología-de-la-síntesis-de-evidencia" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>1. Fundamentos y Tipología de la Síntesis de Evidencia</h1>

</section>
<section id="la-necesidad-de-síntesis-en-biología" class="slide level2">
<h2>La Necesidad de Síntesis en Biología</h2>
<ul>
<li><p><strong>Acumulación exponencial de literatura:</strong> Imposibilidad de abarcar todo el conocimiento con revisiones narrativas tradicionales.</p></li>
<li><p><strong>Riesgos de las Revisiones Narrativas:</strong></p>
<ul>
<li><p>Sesgo de selección explícito o implícito.</p></li>
<li><p>Subjetividad e imposibilidad de réplica.</p></li>
</ul></li>
</ul>
<div class="callout callout-note callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Alternativa</strong></p>
</div>
<div class="callout-content">
<p>La <strong>Revisión Sistemática</strong> garantiza transparencia, reproducibilidad y rigor metodológico.</p>
</div>
</div>
</div>
</section>
<section id="taxonomía-de-la-síntesis-de-evidencia" class="slide level2 smaller">
<h2>Taxonomía de la Síntesis de Evidencia</h2>
<table class="caption-top">
<colgroup>
<col style="width: 17%">
<col style="width: 28%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Tipo</strong></th>
<th><strong>Objetivo Principal</strong></th>
<th><strong>Evaluación de Sesgo</strong></th>
<th><strong>Tipo de Síntesis</strong></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Revisión Sistemática</strong></td>
<td>Responder preguntas específicas de eficacia/impacto</td>
<td>Obligatoria e intensiva</td>
<td>Cualitativa o Cuantitativa</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Metaanálisis</strong></td>
<td>Combinar estimadores numéricos para un efecto global</td>
<td>Obligatoria (ponderación)</td>
<td>Estadística (Efectos Mixtos)</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Scoping Review</strong></td>
<td>Mapear conceptos clave y vacíos de conocimiento</td>
<td>Opcional / No requerida</td>
<td>Descriptiva y Temática</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Systematic Map</strong></td>
<td>Catalogar bases de datos de evidencia primaria</td>
<td>Opcional (Metadatos)</td>
<td>Mapas teóricos e interactivos</td>
<td></td>
</tr>
<tr class="odd">
<td><strong>Rapid Review</strong></td>
<td>Síntesis acelerada para decisiones urgentes</td>
<td>Simplificada / Restringida</td>
<td>Narrativa o Metaanálisis preliminar</td>
<td></td>
</tr>
<tr class="even">
<td><strong>Living Review</strong></td>
<td>Actualización continua ante rápida evolución</td>
<td>Continua y dinámica</td>
<td>Repositorios dinámicos</td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="particularidades-en-biología-vs.-biomedicina" class="slide level2">
<h2>Particularidades en Biología vs.&nbsp;Biomedicina</h2>
<ul>
<li><p><strong>Biomedicina humana:</strong></p>
<ul>
<li><p>Predominio de Ensayos Controlados Aleatorizados (ECA).</p></li>
<li><p>Enfoque monoespecífico (<em>Homo sapiens</em>).</p></li>
</ul></li>
<li><p><strong>Biología y Ecología:</strong></p>
<ul>
<li><p>Heterogeneidad multinivel (taxones, ecotipos, niveles tróficos).</p></li>
<li><p>Diseños predominantemente observacionales o de campo.</p></li>
<li><p><strong>Objetivo:</strong> Quantificar patrones globales, explorar la heterogeneidad (<span class="math inline">\(I^2\)</span>) y evaluar moderadores ecológicos.</p></li>
</ul></li>
</ul>
</section></section>
<section>
<section id="marcos-conceptuales-y-estándares" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>2. Marcos Conceptuales y Estándares</h1>

</section>
<section id="formulación-de-preguntas-pico-vs.-peco" class="slide level2">
<h2>Formulación de Preguntas: PICO vs.&nbsp;PECO</h2>
<p>La mayoría de estudios biológicos evalúan <em>exposiciones a factores estresantes</em> en lugar de intervenciones médicas directas.</p>
<ul>
<li><p><strong>PICO</strong> (Clínico): <em>Population, Intervention, Comparison, Outcome</em></p></li>
<li><p><strong>PECO</strong> (Ecológico/Ambiental): <em>Population, Exposure, Comparison, Outcome</em></p></li>
</ul>
<h3 id="ejemplo-aplicado-peco">Ejemplo Aplicado (PECO):</h3>
<ul>
<li><p><strong>P:</strong> Comunidades de ectotermos terrestres en el Neotrópico.</p></li>
<li><p><strong>E:</strong> Incremento de <span class="math inline">\(+2^\circ\text{C}\)</span> en la temperatura media marina.</p></li>
<li><p><strong>C:</strong> Registros térmicos basales / sitios de control no alterados.</p></li>
<li><p><strong>O:</strong> Tasa de fecundidad y cambio en la diversidad funcional.</p></li>
</ul>
</section>
<section id="otros-marcos-de-pregunta" class="slide level2">
<h2>Otros Marcos de Pregunta</h2>
<ul>
<li><p><strong>PEO</strong> (<em>Population, Exposure, Outcome</em>):</p>
<ul>
<li>Prescinde del comparador explícito cuando no hay sitio de control en hábitats naturales.</li>
</ul></li>
<li><p><strong>SPIDER</strong> (<em>Sample, Phenomenon of Interest, Design, Evaluation, Research type</em>):</p>
<ul>
<li>Orientado a estudios cualitativos, conductuales o etológicos.</li>
</ul></li>
<li><p><strong>PCC</strong> (<em>Population, Concept, Context</em>):</p>
<ul>
<li>Utilizado en Revisiones de Alcance (<em>Scoping Reviews</em>).</li>
</ul></li>
</ul>
</section>
<section id="estándares-de-reporte-roses-y-prisma-ecoevo" class="slide level2">
<h2>Estándares de Reporte: ROSES y PRISMA-EcoEvo</h2>
<p>La declaración PRISMA tradicional presenta limitaciones al abordar la no independencia de datos ecológicos.</p>
<div class="columns">
<div class="column" style="width:50%;">
<h3 id="roses"><strong>ROSES</strong></h3>
<p><em>RepOrting standards for Systematic Evidence Syntheses</em></p>
<ul>
<li><p>Desarrollado por la CEE<sup>1</sup>.</p></li>
<li><p>Formularios específicos para revisiones y mapas sistemáticos ambientales.</p></li>
<li><p>Auditoría rigurosa de estrategias de búsqueda.</p></li>
</ul>
</div><div class="column" style="width:50%;">
<h3 id="prisma-ecoevo"><strong>PRISMA-EcoEvo</strong></h3>
<p><em>Extensión oficial para Ecología y Evolución</em></p>
<ul>
<li><p>Lista de verificación de 27 ítems.</p></li>
<li><p>Registro explícito de no independencia (filogenia, medidas repetidas).</p></li>
<li><p>Exige compartir códigos e insumos estadísticos abiertos.</p></li>
</ul>
</div></div>
<aside><ol class="aside-footnotes"><li id="fn1"><p><em>Collaboration for Environmental Evidence</em></p></li></ol></aside></section></section>
<section>
<section id="fases-metodológicas-de-la-revisión-sistemática" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>3. Fases Metodológicas de la Revisión Sistemática</h1>

</section>
<section id="flujo-metodológico" class="slide level2">
<h2>Flujo Metodológico</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<p><img data-src="revisiones_sistematicas_files/figure-revealjs/mermaid-figure-1.png" style="width:13in;height:4.07in"></p>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>

<aside><div>
<p><a href="https://osf.io/" class="external" target="_blank">OSF (Open Science Framework)</a></p>
<p><a href="https://www.crd.york.ac.uk/prospero/" class="external" target="_blank">PROSPERO</a></p>
<p><a href="https://environmentalevidence.org/ceesat/" class="external" target="_blank">CEESAT (Collaboration for Environmental Evidence Synthesis Appraisal Tool)</a></p>
</div></aside></section>
<section id="estrategia-de-búsqueda-y-selección" class="slide level2">
<h2>Estrategia de Búsqueda y Selección</h2>
<ul>
<li><p><strong>Ecuaciones de Búsqueda:</strong></p>
<ul>
<li><p>Uso de operadores booleanos (<code>AND</code>, <code>OR</code>, <code>NOT</code>), comodines (<code>*</code>), y proximidad.</p></li>
<li><p>Bases de datos: Web of Science, Scopus, PubMed, Google Scholar.</p></li>
</ul></li>
<li><p><strong>Literatura Gris:</strong></p>
<ul>
<li><p>Informes gubernamentales, tesis doctorales, repositorios de preprints.</p></li>
<li><p>Indispensable para contrarrestar el <strong>sesgo de publicación</strong>.</p></li>
</ul></li>
<li><p><strong>Criba e Inter-evaluador:</strong></p>
<ul>
<li><p>Criba por al menos 2 evaluadores independientes en ciego.</p></li>
<li><p>Medición del acuerdo mediante el coeficiente <strong>Kappa de Cohen (</strong><span class="math inline">\(\kappa\)</span><strong>)</strong>.</p></li>
</ul></li>
</ul>
</section></section>
<section>
<section id="síntesis-cuantitativa-y-metaanálisis" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>4. Síntesis Cuantitativa y Metaanálisis</h1>

</section>
<section id="métricas-de-tamaño-del-efecto" class="slide level2 smaller">
<h2>Métricas de Tamaño del Efecto</h2>
<h3 id="razón-de-respuesta-logarítmica-ln-rr">1. Razón de Respuesta Logarítmica (<span class="math inline">\(\ln RR\)</span>)</h3>
<p><span class="math display">\[
\ln RR = \ln\left(\frac{\bar{X}_E}{\bar{X}_C}\right), \quad v_{\ln RR} = \frac{S_E^2}{n_E \bar{X}_E^2} + \frac{S_C^2}{n_C \bar{X}_C^2}
\]</span></p>
<ul>
<li>Expresa el cambio proporcional respecto al control.</li>
</ul>
<h3 id="diferencia-de-medias-estandarizada-g-de-hedges">2. Diferencia de Medias Estandarizada (<span class="math inline">\(g\)</span> de Hedges)</h3>
<p><span class="math display">\[
g = J \times \left( \frac{\bar{X}_E - \bar{X}_C}{S_{pooled}} \right), \quad J = 1 - \frac{3}{4(n_E + n_C - 2) - 1}
\]</span></p>
<ul>
<li>Corrige la sobreestimación en muestras pequeñas mediante el factor <span class="math inline">\(J\)</span>.</li>
</ul>
<h3 id="razón-logarítmica-de-varianzas-ln-vr">3. Razón Logarítmica de Varianzas (<span class="math inline">\(\ln VR\)</span>)</h3>
<ul>
<li>Mide el impacto en la plasticidad fenotípica o variabilidad intra-tratamiento.</li>
</ul>
</section>
<section id="modelos-multinivel-y-dependencia-estadística" class="slide level2">
<h2>Modelos Multinivel y Dependencia Estadística</h2>
<p>Los datos biológicos violan el supuesto de independencia:</p>
<ol type="1">
<li><p>Múltiples efectos dentro de un mismo artículo (efecto de estudio).</p></li>
<li><p>Estructura de filogenia compartida entre especies (matriz de covarianza filogenética).</p></li>
</ol>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-label="1"></a><span class="co"># Ejemplo de ajuste multinivel en R con metafor</span></span>
<span id="cb1-2"><a aria-label="2"></a><span class="fu">library</span>(metafor)</span>
<span id="cb1-3"><a aria-label="3"></a></span>
<span id="cb1-4"><a aria-label="4"></a>model_ml <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(</span>
<span id="cb1-5"><a aria-label="5"></a>  <span class="at">yi =</span> lnRR, </span>
<span id="cb1-6"><a aria-label="6"></a>  <span class="at">V =</span> var_lnRR, </span>
<span id="cb1-7"><a aria-label="7"></a>  <span class="at">random =</span> <span class="fu">list</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> study_id, <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> es_id, <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> species_phylo),</span>
<span id="cb1-8"><a aria-label="8"></a>  <span class="at">R =</span> <span class="fu">list</span>(<span class="at">species_phylo =</span> phylo_cor_matrix),</span>
<span id="cb1-9"><a aria-label="9"></a>  <span class="at">data =</span> dataset_bio</span>
<span id="cb1-10"><a aria-label="10"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="visualización-moderna-orchard-2.0" class="slide level2">
<h2>Visualización Moderna: <code>orchaRd</code> 2.0</h2>
<p>Sustituye los gráficos de bosque (<em>forest plots</em>) por <strong>gráficos de orquídea (<em>orchard plots</em>)</strong>:</p>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li><p><strong>Intervalo de Confianza (95% IC):</strong> Precisión del estimador global.</p></li>
<li><p><strong>Intervalo de Predicción (95% IP):</strong> Rango esperado para futuros estudios primarios (heterogeneidad biológica real).</p></li>
<li><p><strong>Beeswarm (Diagrama de abejas):</strong> Despliega cada tamaño de efecto <span class="math inline">\(y_i\)</span> con tamaño proporcional a su precisión (<span class="math inline">\(1/SE\)</span>).</p></li>
<li><p><strong>Métricas:</strong> Calcula la heterogeneidad multinivel <span class="math inline">\(I^2_{ml}\)</span> y <span class="math inline">\(R^2_{ml}\)</span>.</p></li>
</ul>
</div><div class="column" style="width:40%;">
<p><img data-src="https://figures.semanticscholar.org/2d09fe92a6753684948f9b025707fcfe50c3fa62/9-Figure4-1.png" height="600"></p>
</div></div>
</section></section>
<section>
<section id="herramientas-digitales-e-ia" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>5. Herramientas Digitales e IA</h1>

</section>
<section id="ecosistema-de-software-especializado" class="slide level2">
<h2>Ecosistema de Software Especializado</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th><strong>Plataforma</strong></th>
<th><strong>Tipo de Acceso</strong></th>
<th><strong>Enfoque Principal</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><a href="https://www.cadima.info/" class="external" target="_blank"><strong>CADIMA</strong></a></td>
<td>Gratuito (CEE/JKI)</td>
<td>Flujo completo en ecología, agronomía y ciencias ambientales</td>
</tr>
<tr class="even">
<td><a href="https://www.covidence.org/" class="external" target="_blank"><strong>Covidence</strong></a></td>
<td>Comercial (Cochrane)</td>
<td>Criba y extracción colaborativa con ciego automático</td>
</tr>
<tr class="odd">
<td><a href="https://www.rayyan.ai/" class="external" target="_blank"><strong>Rayyan</strong></a></td>
<td>Freemium</td>
<td>Criba rápida de títulos/resúmenes en entorno móvil y web</td>
</tr>
<tr class="even">
<td><a href="https://asreview.nl/" class="external" target="_blank"><strong>ASReview</strong></a></td>
<td>Código Abierto</td>
<td>Criba asistida por Machine Learning (Aprendizaje Activo)</td>
</tr>
<tr class="odd">
<td><a href="https://www.metafor-project.org/doku.php/metafor" class="external" target="_blank"><strong><code>metafor</code></strong></a> <strong>&amp;</strong> <a href="https://daniel1noble.github.io/orchaRd/" class="external" target="_blank"><strong><code>orchaRd</code></strong></a></td>
<td>R / Gratuito</td>
<td>Modelado estadístico multinivel, filogenético y visualización</td>
</tr>
</tbody>
</table>
</section>
<section id="inteligencia-artificial-en-el-flujo-de-trabajo" class="slide level2">
<h2>Inteligencia Artificial en el Flujo de Trabajo</h2>
<ul>
<li><p><strong>Formulación y Búsqueda:</strong> Traducción de PECO a sintaxis complejas.</p></li>
<li><p><strong>Criba Inteligente:</strong> Reordenamiento por relevancia en tiempo real mediante aprendizaje activo.</p></li>
<li><p><strong>Extracción Automática:</strong> Lectura de tablas en PDF y extracción de datos cuantitativos (<span class="math inline">\(n, \bar{X}, SD\)</span>).</p></li>
<li><p><strong>Marcos de Reporte para IA:</strong> PRISMA-trAIce garantiza la trazabilidad del trabajo híbrido entre humanos y algoritmos.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div>
<p></p><figure class=""><p></p>
<div>
<p><img data-src="revisiones_sistematicas_files/figure-revealjs/mermaid-figure-2.png" style="width:15in;height:2.78in"></p>
</div>
<p></p></figure><p></p>
</div>
</div>
</div>

<aside><div>
<p>El soporte con herramientas basadas en IA permite reducir la carga de trabajo manual entre un <strong>50% y un 75%</strong>.</p>
</div></aside></section></section>
<section>
<section id="desafíos-éticos-e-implicaciones" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>6. Desafíos Éticos e Implicaciones</h1>

</section>
<section id="riesgos-y-limitaciones-de-la-ia" class="slide level2">
<h2>Riesgos y Limitaciones de la IA</h2>
<ul>
<li><p><strong>Sesgo Algorítmico:</strong></p>
<ul>
<li><p>Los modelos LLM heredan sesgos taxonómicos y geográficos globales.</p></li>
<li><p>Riesgo de descartar investigación regional o de especies no modelo.</p></li>
</ul></li>
<li><p><strong>“Alucinaciones” y Fabricación de Datos:</strong></p>
<ul>
<li><p>Confusión entre SD y SE, o invención de números/citas.</p></li>
<li><p>Un solo dato erróneo altera el cálculo del modelo multinivel.</p></li>
</ul></li>
<li><p><strong>Caja Negra e Irreproducibilidad:</strong></p>
<ul>
<li><p>Cambios no documentados en modelos comerciales cerrados.</p></li>
<li><p>Exige publicar <em>prompts</em>, parámetros de temperatura y versiones de la API<sup>1</sup>.</p></li>
</ul></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn2"><p><em>Application Programming Interface</em></p></li></ol></aside></section>
<section id="principio-de-responsabilidad-humana" class="slide level2">
<h2>Principio de Responsabilidad Humana</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Directriz Consensuada (Cochrane / CEE)</strong></p>
</div>
<div class="callout-content">
<p>La Inteligencia Artificial es una <strong>herramienta de soporte a la decisión (<em>decision-support tool</em>)</strong>.</p>
<p>Las decisiones metodológicas sustantivas, la evaluación final de sesgos y la interpretación teórica son <strong>responsabilidad inalienable de los investigadores humanos</strong>.</p>
</div>
</div>
</div>

<img data-src="https://papersflow.ai/blog/systematic-literature-review-ai-agents.webp" class="quarto-figure quarto-figure-center r-stretch"></section></section>
<section>
<section id="ejemplos-en-biología" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>7. Ejemplos en Biología</h1>

</section>
<section id="ejemplo-práctico-1-metaanálisis-multinivel-en-biología-de-conservación-y-cambio-climático" class="slide level2">
<h2>Ejemplo Práctico 1: Metaanálisis Multinivel en Biología de Conservación y Cambio Climático</h2>
<h3 id="título-de-la-investigación">Título de la Investigación</h3>
<p><em>Efectos del estrés térmico por olas de calor marinas en la tasa de blanqueamiento y la calcificación de corales escleractinios (Scleractinia) en arrecifes tropicales: Una revisión sistemática y metaanálisis multinivel.</em></p>

<img data-src="https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/Moofushi_bleached_corals.JPG/500px-Moofushi_bleached_corals.JPG" class="r-stretch quarto-figure-center"><p class="caption">A part of Moofushi’s bleached coral reef (Alifu Dhaalu Atoll, Maldives), damaged by warming sea temperatures. It was strongly hit by 1998’s El Niño; no live coral is still practically visible 8 years later. <a href="https://commons.wikimedia.org/wiki/File:Moofushi_bleached_corals.JPG#/media/File:Moofushi_bleached_corals.JPG" data-targe="_blank">Fuente</a></p></section>
<section id="paso-1-definición-operativa-de-la-pregunta-peco-y-registro-del-protocolo" class="slide level2 smaller">
<h2>Paso 1: Definición Operativa de la Pregunta (PECO) y Registro del Protocolo</h2>
<ol type="1">
<li><strong>Población (P):</strong> Colonias adultas de corales escleractinios formadores de arrecifes pertenecientes a las familias <em>Acroporidae</em> y <em>Poritidae</em> en zonas arrecifales tropicales.</li>
<li><strong>Exposición (E):</strong> Eventos de estrés térmico definidos como olas de calor marinas donde la temperatura superficial del mar (SST) excede en <span class="math inline">\(\ge +1.5\text{ }^\circ\text{C}\)</span> la media máxima estival histórica por una duración continua de <span class="math inline">\(\ge 14\)</span> días.</li>
<li><strong>Comparador (C):</strong> Colonias conspecíficas o controles dentro del mismo hábitat expuestas a condiciones térmicas basales estivales normales (<span class="math inline">\(0\text{ }^\circ\text{C}\)</span> de anomalía).</li>
<li><strong>Resultados / Outcomes (O):</strong></li>
</ol>
<ul>
<li><em>Resultado Primario:</em> Tasa de blanqueamiento coralino, medida como el porcentaje de densidad celular de zooxantelas (<em>Symbiodiniaceae</em>) perdidas por <span class="math inline">\(\text{cm}^2\)</span> o la disminución en la concentración de clorofila <span class="math inline">\(a\)</span> (<span class="math inline">\(\mu\text{g cm}^{-2}\)</span>).</li>
<li><em>Resultado Secundario:</em> Tasa de calcificación neta del esqueleto coralino expresada en <span class="math inline">\(\text{g CaCO}_3\text{ cm}^{-2}\text{ año}^{-1}\)</span>.</li>
</ul>
<ol start="5" type="1">
<li><strong>Registro Prospectivo del Protocolo:</strong> Registrado en la plataforma <em>Open Science Framework</em> (OSF) antes de iniciar la criba bibliográfica (DOI: <code>10.17605/OSF.IO/EXAMPLE_CORAL_2026</code>).</li>
</ol>
</section>
<section id="paso-2-cadena-sintáctica-de-búsqueda-y-literatura-gris" class="slide level2">
<h2>Paso 2: Cadena Sintáctica de Búsqueda y Literatura Gris</h2>
<p>Se diseñó una ecuación sintáctica estructurada ejecutada en <em>Web of Science Core Collection</em>, <em>Scopus</em>, y <em>PubMed</em>:</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb2-1"><a aria-label="1"></a>("Scleractinia" OR "coral reef*" OR "Acropora*" OR "Porites*")</span>
<span id="cb2-2"><a aria-label="2"></a>AND ("thermal stress" OR "marine heatwave*" OR "ocean warming" OR "elevated temperature")</span>
<span id="cb2-3"><a aria-label="3"></a>AND ("bleaching" OR "zooxanthellae loss" OR "calcification" OR "calcification rate")</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>Para controlar el sesgo de publicación, se consultaron tres fuentes de literatura gris:</p>
<ul>
<li><p>Informes técnicos de la <em>National Oceanic and Atmospheric Administration</em> (NOAA Coral Reef Watch).</p></li>
<li><p>Actas de congresos de la <em>International Coral Reef Society</em> (ICRS).</p></li>
<li><p>Repositorios de preprints (<em>bioRxiv</em> y <em>ecoEvoRxiv</em>).</p></li>
</ul>
</section>
<section id="paso-3-criba-e-inter-evaluación-bajo-prisma-traice" class="slide level2">
<h2>Paso 3: Criba e Inter-evaluación bajo PRISMA-trAIce</h2>
<ol type="1">
<li><strong>Fase de Calibración:</strong> Dos investigadores y el módulo de aprendizaje activo de <em>ASReview</em> evaluaron una muestra de 150 resúmenes obteniendo un coeficiente de concordancia de <span class="math inline">\(\kappa = 0.82\)</span>.</li>
<li><strong>Criba de Títulos y Resúmenes:</strong> Criba de 1,170 registros desduplicados en CADIMA, seleccionando 140 artículos a texto completo.</li>
<li><strong>Evaluación en Texto Completo:</strong> Selección final de 38 estudios primarios independientes que aportaron 112 tamaños del efecto cuantitativos.</li>
</ol>
</section>
<section id="paso-4-evaluación-de-riesgo-de-sesgo-con-ceesat" class="slide level2">
<h2>Paso 4: Evaluación de Riesgo de Sesgo con CEESAT</h2>
<p>Cada estudio fue evaluado con la herramienta CEESAT<sup>1</sup> analizando:</p>
<ul>
<li><p>Aleatoriedad en la selección de colonias y existencia de sitios de control.</p></li>
<li><p>Control de variables confusoras (irradiancia solar PAR y flujo de agua).</p></li>
<li><p>Calibración de sensores de temperatura <em>in situ</em>.</p></li>
</ul>
<aside><ol class="aside-footnotes"><li id="fn3"><p><em>Collaboration for Environmental Evidence Synthesis Appraisal Tool</em></p></li></ol></aside></section>
<section id="paso-5-extracción-de-datos-y-métricas-de-tamaño-del-efecto" class="slide level2 smaller">
<h2>Paso 5: Extracción de Datos y Métricas de Tamaño del Efecto</h2>
<table class="caption-top">
<colgroup>
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Estudio Primario</th>
<th style="text-align: left;">Taxón / Especie</th>
<th style="text-align: left;">Región</th>
<th style="text-align: left;">Anomalía (°C)</th>
<th style="text-align: left;"><span class="math inline">\(\bar{X}_E\)</span> (%)</th>
<th style="text-align: left;"><span class="math inline">\(S_E\)</span></th>
<th style="text-align: left;"><span class="math inline">\(n_E\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\bar{X}_C\)</span> (%)</th>
<th style="text-align: left;"><span class="math inline">\(S_C\)</span></th>
<th style="text-align: left;"><span class="math inline">\(n_C\)</span></th>
<th style="text-align: left;"><span class="math inline">\(\ln RR\)</span></th>
<th style="text-align: left;"><span class="math inline">\(v_{\ln RR}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">García et al.&nbsp;(2021)</td>
<td style="text-align: left;"><em>Acropora palmata</em></td>
<td style="text-align: left;">Caribe</td>
<td style="text-align: left;"><span class="math inline">\(+2.0\)</span></td>
<td style="text-align: left;">68.5</td>
<td style="text-align: left;">12.1</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">12.3</td>
<td style="text-align: left;">4.2</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">1.717</td>
<td style="text-align: left;">0.0099</td>
</tr>
<tr class="even">
<td style="text-align: left;">Muñoz &amp; Silva (2022)</td>
<td style="text-align: left;"><em>Porites astreoides</em></td>
<td style="text-align: left;">Caribe</td>
<td style="text-align: left;"><span class="math inline">\(+2.0\)</span></td>
<td style="text-align: left;">34.2</td>
<td style="text-align: left;">8.5</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">10.1</td>
<td style="text-align: left;">3.1</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">1.220</td>
<td style="text-align: left;">0.0125</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Chen et al.&nbsp;(2023)</td>
<td style="text-align: left;"><em>Acropora cervicornis</em></td>
<td style="text-align: left;">Indo-Pacífico</td>
<td style="text-align: left;"><span class="math inline">\(+2.5\)</span></td>
<td style="text-align: left;">82.0</td>
<td style="text-align: left;">10.4</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">8.5</td>
<td style="text-align: left;">2.8</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">2.267</td>
<td style="text-align: left;">0.0063</td>
</tr>
</tbody>
</table>
<h3 id="demostración-matemática-de-ejemplo-para-garcía-et-al.-2021">Demostración Matemática de ejemplo para García et al.&nbsp;(2021)</h3>
<p><span class="math display">\[\ln RR = \ln\left(\frac{68.5}{12.3}\right) = \ln(5.5691) \approx 1.717\]</span></p>
<p><span class="math display">\[v_{\ln RR} = \frac{12.1^2}{15 \times 68.5^2} + \frac{4.2^2}{15 \times 12.3^2} = \frac{146.41}{70383.75} + \frac{17.64}{2269.35} \approx 0.0099\]</span></p>
</section>
<section id="paso-6-script-de-ejecución-en-r-para-el-modelo-multinivel" class="slide level2">
<h2>Paso 6: Script de Ejecución en R para el Modelo Multinivel</h2>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-label="1"></a><span class="fu">library</span>(metafor)</span>
<span id="cb3-2"><a aria-label="2"></a><span class="fu">library</span>(orchaRd)</span>
<span id="cb3-3"><a aria-label="3"></a></span>
<span id="cb3-4"><a aria-label="4"></a><span class="co"># 1. Ajustar modelo metaanalítico multinivel con covarianza filogenética</span></span>
<span id="cb3-5"><a aria-label="5"></a>model_corales <span class="ot">&lt;-</span> <span class="fu">rma.mv</span>(</span>
<span id="cb3-6"><a aria-label="6"></a>  <span class="at">yi =</span> lnRR, </span>
<span id="cb3-7"><a aria-label="7"></a>  <span class="at">V =</span> v_lnRR, </span>
<span id="cb3-8"><a aria-label="8"></a>  <span class="at">mods =</span> <span class="sc">~</span> Anomalia_Termica <span class="sc">+</span> Region,</span>
<span id="cb3-9"><a aria-label="9"></a>  <span class="at">random =</span> <span class="fu">list</span>(<span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> ID_Estudio, <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> ID_Efecto, <span class="sc">~</span> <span class="dv">1</span> <span class="sc">|</span> Especie_Phylo),</span>
<span id="cb3-10"><a aria-label="10"></a>  <span class="at">R =</span> <span class="fu">list</span>(<span class="at">Especie_Phylo =</span> phylo_matrix),</span>
<span id="cb3-11"><a aria-label="11"></a>  <span class="at">data =</span> datos_corales,</span>
<span id="cb3-12"><a aria-label="12"></a>  <span class="at">method =</span> <span class="st">"REML"</span></span>
<span id="cb3-13"><a aria-label="13"></a>)</span>
<span id="cb3-14"><a aria-label="14"></a></span>
<span id="cb3-15"><a aria-label="15"></a><span class="co"># 2. Resumen estadístico</span></span>
<span id="cb3-16"><a aria-label="16"></a><span class="fu">summary</span>(model_corales)</span>
<span id="cb3-17"><a aria-label="17"></a></span>
<span id="cb3-18"><a aria-label="18"></a><span class="co"># 3. Visualización con Gráfico de Orquídea (orchaRd 2.0)</span></span>
<span id="cb3-19"><a aria-label="19"></a><span class="fu">orchard_plot</span>(model_corales, <span class="at">mod =</span> <span class="st">"Region"</span>, <span class="at">group =</span> <span class="st">"ID_Estudio"</span>,</span>
<span id="cb3-20"><a aria-label="20"></a>             <span class="at">xlab =</span> <span class="st">"Razón de Respuesta Logarítmica (lnRR)"</span>,</span>
<span id="cb3-21"><a aria-label="21"></a>             <span class="at">legend.pos =</span> <span class="st">"top.left"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="resultados-estadísticos" class="slide level2">
<h2>Resultados Estadísticos</h2>
<p>El modelo indicó un tamaño del efecto global significativo de <span class="math inline">\(\ln RR = 1.64\)</span> (<span class="math inline">\(95\%\text{ IC} = [1.28, 2.00]\)</span>, <span class="math inline">\(p &lt; 0.001\)</span>), equivalente a un incremento del <span class="math inline">\(+415\%\)</span> en el blanqueamiento.</p>
<p>La heterogeneidad desglosada (<span class="math inline">\(I^2_{ml}\)</span>) asignó <span class="math inline">\(42\%\)</span> a diferencias entre estudios, <span class="math inline">\(28\%\)</span> a la estructura filogenética y <span class="math inline">\(30\%\)</span> al error residual.</p>
</section>
<section id="ejemplo-práctico-2-revisión-sistemática-tradicional-síntesis-cualitativa" class="slide level2">
<h2>Ejemplo Práctico 2: Revisión Sistemática Tradicional (Síntesis Cualitativa)</h2>
<h3 id="título-de-la-investigación-1">Título de la Investigación</h3>
<p><em>Eficacia de las técnicas de restauración ecológica pasiva frente a la activa en la recuperación de servicios ecosistémicos de polinización en agroecosistemas neotropicales degradados: Una revisión sistemática cualitativa bajo el estándar ROSES.</em></p>

<img data-src="https://www.pbs.org/wnet/nature/files/2023/09/Forest-Restoration-Photo-4-scaled-e1694634541736-1280x721.jpg" class="r-stretch quarto-figure-center"><p class="caption">Tree cover being re-established through assisted natural regeneration in recovered cattle pasture in the Maya Biosphere Reserve. Photo credit: ©WCS Guatemala. <a href="https://www.pbs.org/wnet/nature/blog/an-overlooked-opportunity-for-forest-restoration/">Fuente</a></p></section>
<section id="paso-1-definición-de-la-pregunta-peco-y-protocolo-roses" class="slide level2">
<h2>Paso 1: Definición de la Pregunta (PECO) y Protocolo ROSES</h2>
<ol type="1">
<li><strong>Población (P):</strong> Agroecosistemas tropicales y paisajes agrícolas degradados en América Latina.</li>
<li><strong>Exposición / Intervención (E):</strong> Restauración ecológica pasiva (regeneración asistida/exclusión de ganado) frente a activa (siembra de franjas nectaríferas y corredores florales).</li>
<li><strong>Comparador (C):</strong> Monocultivos agrícolas intensivos adyacentes no restaurados o zonas degradadas basales.</li>
<li><strong>Resultados / Outcomes (O):</strong> Recuperación funcional de la polinización (riqueza de polinizadores nativos, tasa de visitas a flores y cuajado de frutos).</li>
<li><strong>Registro del Protocolo:</strong> Registrado en la <em>Collaboration for Environmental Evidence</em> (ID: <code>CEE-26-089</code>).</li>
</ol>
</section>
<section id="paso-2-búsqueda-multilingüe-y-fuentes-registradas" class="slide level2">
<h2>Paso 2: Búsqueda Multilingüe y Fuentes Registradas</h2>
<p>Búsqueda realizada en español, inglés y portugués en <em>Web of Science</em>, <em>SciELO</em>, <em>Redalyc</em>, <em>DOAJ</em> y literatura gris de institutos regionales (Instituto Humboldt, EMBRAPA, CONABIO):</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode numberSource text number-lines code-with-copy"><code class="sourceCode"><span id="cb4-1"><a aria-label="1"></a>("restauración ecológica" OR "ecological restoration" OR "regeneración natural") </span>
<span id="cb4-2"><a aria-label="2"></a>AND ("poliniza*" OR "pollination" OR "abejas" OR "bees") </span>
<span id="cb4-3"><a aria-label="3"></a>AND ("agroecosistema*" OR "agricultural landscape") </span>
<span id="cb4-4"><a aria-label="4"></a>AND ("Neotrópico" OR "América Latina" OR "Neotropics")</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</section>
<section id="paso-3-selección-y-diagrama-roses" class="slide level2">
<h2>Paso 3: Selección y Diagrama ROSES</h2>
<ul>
<li>Registros brutos recuperados: 820.</li>
<li>Registros tras desduplicar: 660.</li>
<li>Excluidos en título/resumen: 510.</li>
<li>Texto completo evaluado: 150 artículos (112 excluidos con causa documentada).</li>
<li><strong>Estudios seleccionados para la síntesis:</strong> 38 estudios primarios cualitativos u observacionales.</li>
</ul>
</section>
<section id="paso-4-justificación-metodológica-de-la-imposibilidad-de-metaanálisis" class="slide level2">
<h2>Paso 4: Justificación Metodológica de la Imposibilidad de Metaanálisis</h2>
<p>Se determinó no realizar síntesis cuantitativa debido a tres barreras metodológicas:</p>
<ol type="1">
<li><strong>Heterogeneidad Métrica Extrema:</strong> Variabilidad de variables no estandarizables (número de granos de polen por estigma vs.&nbsp;abundancia en trampas <em>pan-trap</em> vs.&nbsp;% aborto de frutos).</li>
<li><strong>Ausencia de Medidas de Dispersión:</strong> El <span class="math inline">\(60\%\)</span> de los reportes técnicos de literatura gris omitió la desviación estándar (<span class="math inline">\(SD\)</span>), error estándar (<span class="math inline">\(SE\)</span>) o tamaños muestrales (<span class="math inline">\(n\)</span>).</li>
<li><strong>Mezcla de Diseños:</strong> Incompatibilidad entre experimentos manipulativos de campo e inventarios etnoecológicos cualitativos.</li>
</ol>
</section>
<section id="paso-5-matriz-cualitativa-de-evidencia-y-síntesis-narrativa" class="slide level2 smaller scrollable">
<h2>Paso 5: Matriz Cualitativa de Evidencia y Síntesis Narrativa</h2>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Categoría de Restauración</th>
<th>Ecosistema / Cultivo</th>
<th>Estudios (<span class="math inline">\(n\)</span>)</th>
<th>Dirección del Efecto</th>
<th>Consenso Cualitativo y Mecanismos</th>
<th>Calidad CEESAT</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Restauración Activa:</strong> Franjas florales</td>
<td>Cafetales y frutales</td>
<td>16</td>
<td>14 Positivo, 2 Neutro</td>
<td>Aumento en la riqueza de abejas nativas (<em>Meliponini</em>). La oferta de recursos florales previene cuellos de botella en sequía.</td>
<td><strong>Alta</strong> (Bajo riesgo de sesgo)</td>
</tr>
<tr class="even">
<td><strong>Restauración Pasiva:</strong> Exclusión de ganado</td>
<td>Bosque seco / Pastizales</td>
<td>12</td>
<td>7 Positivo, 4 Neutro, 1 Negativo</td>
<td>Recuperación lenta de la red de interacción. Eficaz únicamente con bosque nativo adyacente a <span class="math inline">\(&lt; 500\text{ m}\)</span>.</td>
<td><strong>Moderada</strong></td>
</tr>
<tr class="odd">
<td><strong>Plantaciones Mixtas:</strong> Árboles nativos</td>
<td>Sistemas agroforestales</td>
<td>10</td>
<td>9 Positivo, 1 Neutro</td>
<td>Incremento en polinizadores de la familia <em>Ceratopogonidae</em>. La sombra y hojarasca optimizan la nidificación.</td>
<td><strong>Alta</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="paso-6-mapeo-de-vacíos-de-evidencia-gap-mapping" class="slide level2">
<h2>Paso 6: Mapeo de Vacíos de Evidencia (<em>Gap Mapping</em>)</h2>
<p>El reporte final bajo la normativa ROSES identificó dos vacíos del conocimiento críticos:</p>
<ul>
<li><strong>Vacío Geográfico:</strong> El <span class="math inline">\(70\%\)</span> de la evidencia se concentra en Brasil y Colombia; escasez total de datos primarios en América Central y el Caribe.</li>
<li><strong>Vacío Taxonómico:</strong> Sesgo del <span class="math inline">\(85\%\)</span> de los estudios hacia abejas (<em>Apis mellifera</em> y <em>Meliponini</em>), ignorando el rol funcional de dípteros, coleópteros y quirópteros.</li>
</ul>
</section></section>
<section>
<section id="conclusiones" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1>8. Conclusiones</h1>

</section>
<section id="puntos-clave" class="slide level2 smaller">
<h2>Puntos Clave</h2>
<ol type="1">
<li><p>La investigación biológica requiere estándares adaptados (<strong>ROSES</strong>, <strong>PRISMA-EcoEvo</strong>) para abordar la complejidad ecológica y filogenética.</p></li>
<li><p>Los modelos metaanalíticos multinivel y las herramientas modernas de visualización (<code>orchaRd</code>) son indispensables para manejar datos no independientes.</p></li>
<li><p>La elección entre un metaanálisis cuantitativo y una revisión sistemática cualitativa no depende de la preferencia del investigador, sino de la <strong>homogeneidad de las métricas</strong> y la <strong>calidad del reporte de dispersión</strong> en los estudios primarios.</p></li>
<li><p>La divulgación de datos procesados, scripts estadísticos en R y listas de verificación (<strong>PRISMA-EcoEvo</strong> / <strong>ROSES</strong>) constituye un requisito indispensable para garantizar la replicabilidad científica.</p></li>
<li><p>La Inteligencia Artificial acelera significativamente los flujos de revisión, pero su integración debe guiarse bajo normativas como <strong>PRISMA-trAIce</strong>.</p></li>
<li><p>La <strong>supervisión humana experta</strong> sigue siendo la salvaguarda ética y científica fundamental para la síntesis del conocimiento.</p></li>
</ol>
</section></section>
<section id="section" class="title-slide slide level1 center" data-background-color="#1e293b">
<h1></h1>



<img data-src="logo-central.png" width="200" class="r-stretch"></section>


    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1366,

        height: 900,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/rodianfonseca\.github\.io\/revisiones-sistematicas");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>